#ifndef _SYSCALL_NB_COMMON_H_
#define _SYSCALL_NB_COMMON_H_

typedef enum { 
    SYSCALL_TERM_PUTS = 0,
    SYSCALL_TERM_SET_COLORS,
    SYSCALL_KEYB_GET_KEY,
    SYSCALL_TIMER_INFO,
    SYSCALL_TIMER_SLEEP,
    SYSCALL_VBE_FB_INFO,
    SYSCALL_VBE_SETPIX,
    SYSCALL_TASK_EXEC,

    SYSCALL_FILE_STAT,
    SYSCALL_FILE_OPEN,
    SYSCALL_FILE_READ,
    SYSCALL_FILE_CLOSE,
    SYSCALL_FILE_SEEK,
    SYSCALL_FILE_ITERATOR,
    SYSCALL_FILE_HAS_NEXT,
    SYSCALL_FILE_NEXT,

    __SYSCALL_END__
} syscall_t;

#endif
